apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganes-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ganesacr.azurecr.io/ganesclusternodeapp
        ports:
        - containerPort: 80
