  
apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ganescluster2"
spec:
  replicas: 2
  selector:
      matchLabels:
        name: "ganescluster2"
  template:
    metadata:
      labels:
        app: "ganescluster2"
    spec:
      containers:
        - name: "ganescluster2"
          image: "ganesacr.azurecr.io/ganesclusternodeapp"
          ports:
          - containerPort: 80
