apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganes-deploy-part
  labels:
    app: ganescluster2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ganesacr.azurecr.io/ganesclusternodeapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: "ganescluster2-6f7b"
    labels:
        app: "ganescluster2-6f7b"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ganes-deploy-part"

