# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        login-server: ganesacr.azurecr.io
        username: ${{ secrets.ganes_acr_username }}
        password: ${{ secrets.ganes_acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ganesacr.azurecr.io/ganesClusterNodeApp:${{ github.sha }}
        docker push ganesacr.azurecr.io/ganesClusterNodeApp:${{ github.sha }}
        
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ganescluster_kubeConfig }}
      id: login
    
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ganesclusterd44c
        container-registry-url: ganesacr.azurecr.io
        container-registry-username: ${{ secrets.ganes_acr_username }}
        container-registry-password: ${{ secrets.ganes_acr_password }}
        secret-name: ganesclusterdockerauth
      
    - uses: azure/k8s-deploy@users/koushdey/addAnnotationsk8sDeploy
      with:
        namespace: ganesclusterd44c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ganesacr.azurecr.io/ganesClusterNodeApp:${{ github.sha }}
        imagepullsecrets: |
          ganesclusterdockerauth
